* A minor-mode menu for the mode line

This package implements a nested menu that gives access to all known
minor modes (i.e., those listed in ~minor-mode-list~).  It can be used
to toggle local and global minor modes, to access mode-specific menus,
and to display information about modes.

This menu is intended as a replacement for the incomplete, yet quite
space consuming, list of enabled minor modes that is displayed in the
mode line by default.  To use the menu like this, enable Minions mode.

Alternatively the menu can be bound globally, for example:

#+begin_src emacs-lisp
  (keymap-global-set "<S-down-mouse-3>" #'minions-minor-modes-menu)
#+end_src

To list a mode even though the defining library has not been loaded
yet, you must add it to ~minor-mode-list~ yourself.  Additionally it
must be autoloaded.  For example:

#+begin_src emacs-lisp
   (when (autoloadp (symbol-function 'glasses-mode))
     (cl-pushnew 'glasses-mode minor-mode-list))
#+end_src

Compatibility information can be found [[https://github.com/tarsius/minions/wiki][here]].

#+html: <br><br>
#+html: <a href="https://github.com/tarsius/minions/actions/workflows/compile.yml"><img alt="Compile" src="https://github.com/tarsius/minions/actions/workflows/compile.yml/badge.svg"/></a>
#+html: <a href="https://stable.melpa.org/#/minions"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/minions-badge.svg"/></a>
#+html: <a href="https://melpa.org/#/minions"><img alt="MELPA" src="https://melpa.org/packages/minions-badge.svg"/></a>
